apiVersion: telemetry.kyma-project.io/v1alpha1
kind: LogPipeline
metadata:
  name: logpipeline-sample
spec:
  input:
    application:
      namespaces:
        system: true
  output:
    custom: |
      name   loki
      host   loki-example-headless.loki-example.svc.cluster.local
      port   3100
      labels job=fluentbit
      auto_kubernetes_labels on
