loki:
  podLabels:
    sidecar.istio.io/inject: "true"

  # Loki pod resource configuration
  resources:
    limits:
      cpu: 200m
      memory: 300Mi
    requests:
      cpu: 10m
      memory: 128Mi

  # enable persistence volume
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi

  config:
    auth_enabled: false
    limits_config:
      ingestion_rate_mb: 3

    chunk_store_config:
      max_look_back_period: 120h
    table_manager:
      retention_deletes_enabled: true
      retention_period: 120h
grafana:
  enabled: false
promtail:
  enabled: false
