# promtail log collector configuration
promtail:
  enabled: true

  ## Pod Annotations
  podLabels:
    sidecar.istio.io/inject: "true"

  ## Pod Annotations
  podAnnotations:
    sidecar.istio.io/inject: "true"